test:
  uri: 'http://localhost:9393'
development:
  uri: 'http://localhost:9393'
  #uri: 'http://smartstock-api.staging.mshini.com'
staging:
  uri: 'http://staging.smartstock-api.io'
production:
  uri: 'http://smartstock-api.io'
